version: '3'
services:
  mud:
    image: python:3.10
    container_name: pymud-mud
    command: >
      sh -c "pip install -r /requirements.txt
      && python -m spacy download en_core_web_sm
      && alembic upgrade head
      && python /src/data/init_data.py
      ; python /src/pymud.py"
    environment:
      - DB_HOST=pymud-db-dev
      - DB_PORT=5432
      - DB_USER=mud_admin
      - DB_PASSWORD=mud123
      - DB_NAME=mud
      - PYTHONPATH=/:/src
    ports:
      - 5000:5000
    volumes:
      - ../src:/src
      - ../requirements.txt:/requirements.txt
      - ../alembic.ini:/alembic.ini
      - ../migrations:/migrations
    depends_on:
      - db
  db:
    image: postgres:15.3
    container_name: pymud-db-dev
    command: "postgres -c log_statement=all"
    restart: always
    environment:
      - POSTGRES_DB=mud
      - POSTGRES_USER=mud_admin
      - POSTGRES_PASSWORD=mud123
    ports:
      - 9876:5432
