version: '0.1'
name: pymud
services:
  mud:
    image: python:3.10.12-alpine3.18
    command: >
      sh -c "pip install -r /requirements.txt
      && alembic revision --autogenerate
      && alembic upgrade head
      && python /pymud.py"
    environment:
      - DB_HOST=pymud-db-1
      - DB_PORT=5432
      - DB_USER=mud_admin
      - DB_PASSWORD=mud123
      - DB_NAME=mud
      - PYTHONPATH=/:/src
    ports:
      - 5000:5000
    volumes:
      - ../src:/src
      - ../pymud.py:/pymud.py
      - ../requirements.txt:/requirements.txt
      - ../alembic.ini:/alembic.ini
      - ../migrations:/migrations
    depends_on:
      - db
      
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=mud
      - POSTGRES_USER=mud_admin
      - POSTGRES_PASSWORD=mud123
    ports:
      - 9876:5432
